In [1]:
import numpy as np

In [2]:
a=np.array([0,1,2,3])
print(a,'\t',type(a),'\t',a.shape,'\t',a.ndim)

[0 1 2 3] 	 <class 'numpy.ndarray'> 	 (4,) 	 1


In [3]:
b=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(b,'\n',b.ndim,'\t',b.shape,'\t',b.size)
print(b[0],'\t',b[0,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
 2 	 (3, 3) 	 9
[0 1 2] 	 1


In [4]:
a=np.array([0,1,2,3],dtype=np.int64)
print(np.zeros((3,5)))
print(np.asarray([[0,1,2],[3,4,5],[6,7,8]]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
a=np.eye(3)
b=np.asarray(a)
print(b)
a=np.eye(4)
print(b)
b=np.asarray(a)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
a=np.eye(4)
print(a[1:3])

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [7]:
a=np.arange(12)
b=a.reshape(3,4)
print(a)
print(b)
print()
b=a.resize(3,4)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
None


In [8]:
a=np.arange(12).reshape(4,3)
b=np.arange(12).reshape(3,4)
c=np.arange(16).reshape(4,4)
d=np.matmul(np.matmul(a,b),c)+np.eye(4)
print(d)
print(np.transpose(d))
e=np.linalg.inv(d)
print(np.matmul(d,e))

[[ 649.  746.  844.  942.]
 [2016. 2313. 2608. 2904.]
 [3384. 3878. 4373. 4866.]
 [4752. 5444. 6136. 6829.]]
[[ 649. 2016. 3384. 4752.]
 [ 746. 2313. 3878. 5444.]
 [ 844. 2608. 4373. 6136.]
 [ 942. 2904. 4866. 6829.]]
[[ 1.00000000e+00 -1.78745907e-14 -1.10356169e-13 -8.99280650e-15]
 [-8.12683254e-14  1.00000000e+00 -1.67865721e-13 -6.97220059e-14]
 [-2.67008637e-13  4.89608354e-14  1.00000000e+00 -2.15716334e-13]
 [-1.38611345e-13 -7.78821452e-14 -5.23470156e-13  1.00000000e+00]]


In [9]:
a=np.array([[0,1],[1,1]])
b=np.linalg.inv(a)
c=np.matmul(a,b)
print(c)

[[1. 0.]
 [0. 1.]]


In [10]:
a=np.arange(12).reshape(3,4)
print(a)
b=np.sum(a,axis=0)
print(b)
c=np.sum(a,axis=1)
print(c)
d=np.sum(a)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
66


In [11]:
a=np.arange(24).reshape(2,3,4)
print(a)
b=np.sum(a,axis=0)
print(b)
c=np.sum(a,axis=1)
print(c)
d=np.sum(a,axis=2)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


In [12]:
x=np.array([1,2,3])
y=np.array([4,5,6])
a=np.stack((x,y),axis=0)
b=np.stack((x,y),axis=1)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [13]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
m=np.mat(a)
print(m)
print(type(a),type(m))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> <class 'numpy.matrix'>


In [14]:
# np.random.seed(612)

print(np.random.rand(2,3))
print(np.random.rand())
print(np.random.uniform(1,5,(3,2)))
print(np.random.randint(1,5,(3,2)))
print(np.random.randn(2,3))
print(np.random.normal(0,1,(3,2)))

[[0.28254091 0.43162581 0.41536515]
 [0.98414176 0.37263282 0.43056862]]
0.6393977095815186
[[1.32775941 2.06114487]
 [3.41531713 1.65942561]
 [4.40102026 1.20570632]]
[[4 1]
 [4 1]
 [4 2]]
[[-0.54149221  0.37786825 -0.84925821]
 [ 0.94299022  1.01326393 -1.20586141]]
[[ 0.34111764  0.00378178]
 [-0.90316315 -1.13868469]
 [ 0.24366958  0.00294014]]


In [15]:
arr=np.arange(10)
np.random.shuffle(arr)
print(arr)

[1 2 6 0 5 8 9 4 3 7]
