# 实例10.3-TensorFlow创建variable变量

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.Variable(3))
print(tf.Variable([1,2]))
print(tf.Variable(np.array([1,2])))
print(tf.Variable(3.))
print(tf.Variable([1,2],dtype=tf.float64))

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>
<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([1., 2.])>


In [3]:
print(tf.Variable(tf.constant([[1,2],[3,4]])))
print(tf.Variable(tf.zeros([2,3])))
print(tf.Variable(tf.random.normal([2,2])))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.3534131 ,  0.13466921],
       [ 0.516003  , -1.0106306 ]], dtype=float32)>


In [4]:
x=tf.Variable([1,2])
print(x,x.shape,x.dtype)
print(x.numpy())
print(x.trainable,type(x))

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])> (2,) <dtype: 'int32'>
[1 2]
True <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [5]:
y=tf.Variable([1,2])
y.assign([3,4])
print(y)
y.assign_add([1,1])
print(y)
y.assign_sub([1,1])
print(y)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5])>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>


In [6]:
a=tf.range(5)
b=tf.Variable(a)

print(isinstance(a,tf.Tensor),isinstance(a,tf.Variable))
print(isinstance(b,tf.Tensor),isinstance(b,tf.Variable))

True False
False True
